### PR TITLE
Support lists of objects with provided custom mapper

### PR DESCRIPTION
**Pull request by FroznMine**
Currently there is no way to have a list of Objects which are mapped via a custom mapper. The map is simply taken from the database and put into the list. That small change should fill the gap.

### CODE REVIEW

**Comment by sboesebeck** [comment]
Very cool. Would you mind adding a little test for it?

**Comment by FroznMine** [comment]
That shouldn't be a problem. Should I create a new test or add it to the ListTests?

**Comment by sboesebeck** [comment]
Just add a little test to ListTest, this should be fine. Thanks.

**Comment by FroznMine** [comment]
Alright I figured out that the custom mapped objects aren't unpacked in maps neither. I started work to support this. As of this I choose to create an additional test for it.
Currently the change broke some other tests so I'll need to investigate in it. Some of the tests which test the different driver types take very long and haven't finished after more than an hour. That makes it very difficult to test the change. Is there something I have to put attention on?

**Comment by sboesebeck** [comment]
Hi,

yes, the whole testing is a bit too much. But you could concentrate on the basic tests first, like the list, reference and such. Leave the performance and comparison tests aside. I need to figure out some way to create proper test scenarios there and we also need to improve the whole testing process...

**Comment by FroznMine** [comment]
Hi,

thanks for the tips regarding testing, I think I got a proper setup in the last couple days. Anyway it seems my changes currently break some other essential tests, which is bad. I also noticed that there is a lot of code regarding (un-)marshaling which is there twice or more times... Would you mind if I refactor the internals of the implementation if the functionality stays as it is or shouldn't I do this?

**Comment by sboesebeck** [comment]
yes, there are some places of douplicates. We always try to remove them, when seen. Sometimes it's not that easy fix though... 

feel free to reduce duplication, I'm glad you want to help! Thanks a lot!

**Comment by FroznMine** [comment]
There are the remaining two commits that are necessary to make the proposed change work. Feel free to look at it and do whatever you want to do with it.

I'm glad I can help you. Morphium is a great piece of software and I want to use it (switching from Morphia). One great pro is the caching, it's awesome! Basically it all worked quite good but for some things I needed to make some ugly work arounds. Then came the day I didn't want to do that anylonger and decided I will change it, so why not share the work with you.

Occasionally I will create some more pull requests with other things I want to change which I think will be good in the official source too.

**Comment by sboesebeck** [comment]
Hi,

if you have any ugly workarounds left, just tell me. would love to integrate it into morphium. Morphium was built because morphia lacked a lot of things we needed. Caching was one thing. And with morphium we could create a high load application that takes deals with collections of several hundred million entries. And works fine...

I'm really thankful for any help! 

I'll merge it to develop and run the test! Thanks

**Comment by sboesebeck** [comment]
Hi there,

I took a look at your code and I really like it! Thanks a lot for your 
contribution!

Just one minor thing: with `morphium 3.0` we introduced the new driver 
architecture. That means, you could use morphium with almost any non-sql 
database there is (provided you write a driver for it). But, in order to 
avoid problems and be able to somewhen put the drivers in a different 
package for example, we need to reduce the dependencies to for example 
the official mongodb stuff. That is the reason, why we're not dealing 
with `Documents` anymore but use plain old `Map`-implementations 
instead.

Also, in history of the mongodb driver, the change of data structure 
broke our builds several times, so we want to keep the dependencies 
within the drivers package.

Hence I removed the one `Document` that was used in one of the tests. 
Hope that’s ok...

The tests run fine here too! Cool improvements!

Cheers,

Stephan

**Comment by FroznMine** [comment]
Hello,

you're welcome, glad I could improve it.

This upcoming changes sound very interesting, looking forward to hear more soon. The reason I used a 'Document' is that it's very easy to map just one value, which is needed for the type mapper to correctly unwrap everything. Removing this is no problem at all. 

Regarding those other workarounds: I will try to use the new changes in my project and if I got everything working again I will give additional feedback on features I could need.

**Comment by FroznMine** [comment]
Alright this patch isn't completed yet. It fails lists/maps containing parameterized types. Will start working on a fix for this now. Hopefully I get this done today.

**Comment by sboesebeck** [comment]
Ok, no problem. That's what the develop branch is good for. As soon as your changes are stable I'll run all tests and we can prepare a new release.


/s


 From: FroznMine <notifications@github.com> To: sboesebeck/morphium <morphium@noreply.github.com> CC: Stephan Bösebeck <stephan@boesebeck.biz>,  State change <state_change@noreply.github.com> Subject: Re: [sboesebeck/morphium] Support lists of objects with provided custom mapper (#21) Date: 30.05.16, 17:23

 
Alright this patch isn't completed yet. It fails lists/maps containing parameterized types. Will start working on a fix for this now. Hopefully I get this done today.—

**Pull request merged**
